// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyxqswiinxqknkpcpkzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5eHFzd2lpbnhxa25rcGNwa3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODkzMzEsImV4cCI6MjA1Njc2NTMzMX0.A1qvXQvZEQcunh2WDcorXI_4MyZpuW6iXLtWp93Zig0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);